import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "./Navbar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Strype",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <section className="container mx-auto px-4">
      <Navbar />
      <main>{children}</main>
      <Toaster position="top-center" />
    </section>
  );
}
